---
title: Sterren verzamelaar
hero_image: images/banner.png
description:
  - Maak een minigame waar je zo snel als je kunt sprankelende, draaiende sterren
  - verzamelt
meta_title: Learn Unity | Game development | Star collector
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Make a mini game in Unity where you collect spinning stars as fast as you can.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Een draaiende ster
  - 
    title: De ster verzamelen
    completion:
      - engaged
  - 
    title: Sterren tellen
  - 
    title: Tijd bijhouden
    completion:
      - internal
  - 
    title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Verbeter je project
  - 
    title: Wat kun je verder nog doen?
