title: star-collector
hero_image: images/banner.png
description: star-collector description
version: 4
listed: false
copyedit: false
last_tested: "2021-10-19"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
