title: Star collector
hero_image: images/banner.png
description: Make a minigame where you collect sparkling, spinning, stars as fast as you can.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: A spinning star
  - title: Collecting the star
  - title: Counting stars
  - title: Keeping time
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
