---
title: स्टार कलेक्टर
hero_image: images/banner.png
description:
  - Make a minigame where you collect sparkling, spinning, stars as fast
  - as you can
meta_title: Learn Unity | Game development | Star collector
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Make a mini game in Unity where you collect spinning stars as fast as you can.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: You will make
  - 
    title: एक घूमता हुआ तारा
  - 
    title: स्टार इकट्ठा करना
    completion:
      - engaged
  - 
    title: सितारों की गिनती
  - 
    title: समय रखना
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: प्रोजेक्ट को अपग्रेड करें
  - 
    title: आगे क्या है?
