---
title: Coleccionista de estrellas
hero_image: images/banner.png
description: Haz un minijuego en el que recolectas estrellas brillantes que giran lo más rápido que puedas
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - 
    title: Introducción
  - 
    title: Una estrella giratoria
  - 
    title: Recolectando la estrella
    completion:
      - engaged
  - 
    title: Contando estrellas
  - 
    title: Controlando el tiempo
    completion:
      - internal
  - 
    title: Reflexión
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
