---
title: Collectionneur d'étoiles
hero_image: images/banner.png
description:
  - Crée un mini-jeu dans lequel tu collectes des étoiles scintillantes et tournoyantes aussi vite
  - que possible
meta_title: Apprendre Unity | Développement de jeux | Collectionneur d'étoiles
meta_description: Apprends à développer des jeux Unity avec Raspberry Pi Foundation. Crée un mini jeu dans Unity dans lequel tu collectes des étoiles qui tournent le plus vite possible.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: Une étoile tournante
  - 
    title: Collecter l'étoile
    completion:
      - engaged
  - 
    title: Compter les étoiles
  - 
    title: Conserver le temps
    completion:
      - internal
  - 
    title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
