---
title: Collectionneur d'étoiles
hero_image: images/banner.png
description:
  - Make a minigame where you collect sparkling, spinning, stars as fast
  - as you can
meta_title: Learn Unity | Game development | Star collector
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Make a mini game in Unity where you collect spinning stars as fast as you can.
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: Introduction
  - 
    title: Une étoile tournante
  - 
    title: Collecter l'étoile
    completion:
      - engaged
  - 
    title: Compter les étoiles
  - 
    title: Conserver le temps
    completion:
      - internal
  - 
    title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
